"use client";
import Link from 'next/link';
import dynamic from 'next/dynamic';
import { useMemo, useRef, useState } from 'react';
import { Award, ArrowDownToLine, ArrowRight, ArrowUpDown, Braces, Check, ChevronLeft, ChevronRight, Copy, FileSpreadsheet, FileText, Fingerprint, Info, Layers3, LoaderCircle, LockKeyhole, ScanText, Search, ShieldCheck, UploadCloud, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogHeader } from '@/components/ui/dialog';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { flexRender, getCoreRowModel, getPaginationRowModel, getSortedRowModel, useReactTable, type ColumnDef, type SortingState } from '@tanstack/react-table';
import { analyzeText, analyzeBatch, countWords, exportCSV, MODEL_NOTE, type Reviewed, type TextAnalysis } from '@/lib/analysis';
import { autoMapping, readFile, toParticipants, type Imported, type Mapping } from '@/lib/import';
import { QualitySetup, QualityReviewCard } from '@/components/quality-review';
import { DuplicateMatches } from '@/components/duplicate-matches';
import { assessQuality, qualityScore, qualityStatus, rankQuality, QUALITY_NOTE, type QualityAssessment } from '@/lib/quality';

const CertificateStudio=dynamic(()=>import('@/components/certificate-studio'),{ssr:false,loading:()=> <p className="certificate-loading">Menyiapkan studio sertifikat…</p>});

const EXAMPLE='Berikut adalah contoh refleksi tentang budaya inovasi.\n\nDalam pekerjaan sehari-hari, saya melihat bahwa inovasi tidak selalu membutuhkan perubahan besar. Minggu lalu, tim kami masih mengumpulkan permintaan data melalui beberapa percakapan yang terpisah. Akibatnya, ada permintaan yang terlewat dan pekerjaan yang dilakukan dua kali.\n\nSaya mencoba membuat satu formulir sederhana untuk mencatat permintaan, tenggat, dan penanggung jawabnya. Kami baru mengujinya pada tiga permintaan, jadi saya belum bisa menyimpulkan bahwa prosesnya sudah lebih cepat. Minggu depan saya akan meminta masukan dari rekan yang menggunakannya dan membandingkan waktu penyelesaian. Bagi saya, perubahan kecil yang bisa diperiksa hasilnya lebih berguna daripada sekadar meminta semua orang untuk terus berinovasi.';
function download(content:string,filename:string) { const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
function template(){download('\ufeffNama,Grup,Jawaban 1,Jawaban 2,Durasi\r\nPeserta Contoh,Unit A,"Tuliskan refleksi di sini.","Tuliskan rencana tindakan di sini.",5 menit','template-telaah.csv');}

function Findings({result,compact=false}:{result:TextAnalysis;compact?:boolean}) {
 return <div className={compact?'findings compact':'findings'}>
  <div className="result-banner"><span className="eyebrow">TINJAUAN POLA BAHASA</span><h3>{result.label}</h3><p>{result.signals.length ? `${result.signals.length} pola ditemukan. Baca alasannya sebelum menilai.` : 'Tidak ada aturan yang cocok. Ini tidak membuktikan bahwa teks ditulis manusia.'}</p></div>
  <div className="stat-strip"><div><strong>{result.words.toLocaleString('id')}</strong><span>Kata</span></div><div><strong>{result.sentences}</strong><span>Kalimat*</span></div><div><strong>{result.signals.length}</strong><span>Pola ditandai</span></div></div>
  {result.limited&&<div className="inline-note"><Info size={17}/><p>Teks di bawah 80 kata memberi konteks terbatas. Jawaban singkat atau kritis tidak otomatis buruk maupun buatan AI.</p></div>}
  <div className="signals-title"><h4>Alasan yang bisa diperiksa</h4><span>{result.signals.length} pola</span></div>
  {result.signals.length===0?<div className="no-signals"><Check size={21}/><div><strong>Belum ada pola yang ditandai</strong><p>Periksa pengalaman konkret, konteks tugas, dan proses penulisan melalui percakapan dengan penulis.</p></div></div>:result.signals.map((s,i)=><article className="signal" key={s.id}><div className="signal-heading"><span>{String(i+1).padStart(2,'0')}</span><h4>{s.title}</h4></div><p>{s.explanation}</p><div className="evidence">{s.evidence.map((e,j)=><blockquote key={j}>{e}</blockquote>)}</div><p className="signal-caution">{s.caution}</p></article>)}
  <p className="fine-print">* Kalimat dihitung dari tanda baca. Tidak ada pengukuran probabilitas AI.</p>
 </div>
}

function ResultsTable({rows,sourceName,onReview}:{rows:Reviewed[];sourceName:string;onReview:(id:number,quality:QualityAssessment)=>void}) {
 const participantTitleRef=useRef<HTMLHeadingElement>(null);const participantBodyRef=useRef<HTMLDivElement>(null);
 const [pdfBusy,setPdfBusy]=useState(false);const [pdfError,setPdfError]=useState('');
 const [query,setQuery]=useState('');const [status,setStatus]=useState('all');const [sorting,setSorting]=useState<SortingState>([]);const [selectedId,setSelected]=useState<number|null>(null);const [topOnly,setTopOnly]=useState(false);
 const selected=rows.find(row=>row.id===selectedId)??null;const hasQuality=rows.some(row=>row.quality);
 const [pagination,setPagination]=useState({pageIndex:0,pageSize:10});
 const matching=useMemo(()=>rows.filter(r=>`${r.name} ${r.group}`.toLowerCase().includes(query.toLowerCase())&&(status==='all'||(status==='duplicates'&&r.exactCount>1)||(status==='signals'&&r.analysis.signals.length>0)||(status==='short'&&r.analysis.limited)||(status==='reviewed'&&r.quality?.confirmed))),[rows,query,status]);
 const ranked=useMemo(()=>rankQuality(matching),[matching]);
 const filtered=useMemo(()=>hasQuality&&topOnly?ranked.filter(row=>row.qualityRank!==undefined&&row.qualityRank<=10):ranked,[ranked,topOnly,hasQuality]);
 const columns=useMemo<ColumnDef<Reviewed>[]>(()=>{
  const qualityColumns:ColumnDef<Reviewed>[]=hasQuality?[
   {id:'rank',accessorKey:'qualityRank',header:'Peringkat',sortUndefined:'last',cell:({row})=><span className="quality-rank">{row.original.qualityRank?`#${row.original.qualityRank}`:'—'}</span>},
   {id:'quality',accessorFn:row=>row.quality?qualityScore(row.quality):undefined,header:'Kualitas /100',sortUndefined:'last',cell:({row})=>row.original.quality?<button className="quality-cell" onClick={()=>setSelected(row.original.id)}><strong>{qualityScore(row.original.quality)}</strong><small>{qualityStatus(row.original.quality)}</small></button>:<span className="muted">Belum dinilai</span>}
  ]:[];
  return [
  {id:'name',accessorKey:'name',header:'Peserta',cell:({row})=><button className="participant-name" onClick={()=>setSelected(row.original.id)}><span>{row.original.name}</span><small>{row.original.group}</small></button>},
  ...qualityColumns,
  {id:'words',accessorFn:r=>r.analysis.words,header:'Kata',cell:({getValue})=><span className="numeric">{Number(getValue()).toLocaleString('id')}</span>},
  {id:'signals',accessorFn:r=>r.analysis.signals.length,header:'Pola bahasa',cell:({row})=><span className={`status-tag ${row.original.analysis.signals.length?'amber':'neutral'}`}>{row.original.analysis.signals.length?`${row.original.analysis.signals.length} pola ditandai`:'Tidak ditandai'}</span>},
  {id:'duplicates',accessorKey:'exactCount',header:'Jawaban identik',cell:({row})=>row.original.exactCount>1?<span className="duplicate-tag"><Copy size={14}/>{row.original.exactCount} peserta</span>:<span className="muted">{row.original.exactCount===0?'Teks kosong':'Tidak ditemukan'}</span>},
  {id:'details',header:'',cell:({row})=><Button variant="ghost" size="sm" className="detail-btn" aria-label={`Lihat detail ${row.original.name}`} onClick={()=>setSelected(row.original.id)}>Detail<ArrowRight size={15}/></Button>}
 ];},[hasQuality]);
 const table=useReactTable({data:filtered,columns,state:{sorting,pagination},onSortingChange:update=>{setSorting(update);setPagination(p=>({...p,pageIndex:0}));},onPaginationChange:setPagination,getCoreRowModel:getCoreRowModel(),getSortedRowModel:getSortedRowModel(),getPaginationRowModel:getPaginationRowModel(),autoResetPageIndex:false});
 async function exportPDF() {
  if(pdfBusy||!filtered.length)return;
  const exportRows=table.getSortedRowModel().rows.map(row=>row.original);
  const labels:Record<string,string>={all:'Semua hasil',duplicates:'Jawaban identik',signals:'Ada pola bahasa',short:'Teks singkat',reviewed:'Penilaian dikonfirmasi'};
  const orderLabels:Record<string,string>={name:'Nama peserta',words:'Jumlah kata',signals:'Jumlah pola',duplicates:'Jumlah pasangan identik',rank:'Peringkat kualitas',quality:'Skor kualitas'};
  const date=new Date();
  const options={sourceName,totalRows:rows.length,query,filterLabel:`${labels[status]||status}${hasQuality&&topOnly?' · Top 10 + nilai seri':''}`,rankingCount:hasQuality?matching.filter(row=>row.quality).length:undefined,sortLabel:sorting.map(sort=>`${orderLabels[sort.id]||sort.id} (${sort.desc?'menurun':'menaik'})`).join(', ')||'Urutan file sumber',date};
  setPdfBusy(true);setPdfError('');
  try {const {buildBatchReport,loadReportFont,reportFilename}=await import('@/lib/pdf-report');const fontBase64=await loadReportFont();buildBatchReport(exportRows,{...options,fontBase64}).save(reportFilename('peserta',date));}
  catch {setPdfError('PDF belum dapat dibuat. Periksa koneksi untuk memuat pembuat laporan, lalu coba lagi.');}
  finally {setPdfBusy(false);}
 }
 return <section className="batch-results">
  <div className="section-heading"><div><span className="eyebrow">HASIL PEMERIKSAAN</span><h2>Respons peserta</h2></div><div className="export-actions"><Button variant="outline" disabled={!filtered.length} onClick={()=>download(exportCSV(table.getSortedRowModel().rows.map(row=>row.original)),'hasil-telaah.csv')}><ArrowDownToLine size={16}/>Unduh CSV</Button><Button variant="outline" onClick={exportPDF} disabled={pdfBusy||!filtered.length} aria-busy={pdfBusy}>{pdfBusy?<LoaderCircle size={16} className="spin"/>:<FileText size={16}/>}<span>{pdfBusy?'Membuat PDF…':'Unduh PDF'}</span></Button></div></div>
  {pdfError&&<div className="error-message" role="alert"><Info size={18}/><p>{pdfError}</p></div>}
  <div className="batch-stats"><div><Layers3 size={20}/><strong>{rows.length.toLocaleString('id')}</strong><span>Respons diperiksa</span></div><div><Copy size={20}/><strong>{rows.filter(r=>r.exactCount>1).length.toLocaleString('id')}</strong><span>Respons dalam kelompok identik</span></div><div><ScanText size={20}/><strong>{rows.filter(r=>r.analysis.signals.length>0).length.toLocaleString('id')}</strong><span>Respons dengan pola ditandai</span></div></div>
  {hasQuality&&<div className="quality-ranking-banner"><div><h3>Kandidat jawaban terbaik</h3><p>Peringkat dihitung di antara {matching.filter(row=>row.quality).length} respons bernilai dalam filter aktif. Skor yang sama berbagi peringkat; nilai seri pada batas Top 10 ikut ditampilkan. Skor awal dan koreksi reviewer dapat bercampur—gunakan filter penilaian dikonfirmasi untuk hasil yang sudah ditinjau.</p></div><div className="quality-ranking-actions"><Button variant="outline" size="sm" onClick={()=>{setSorting([{id:'quality',desc:true}]);setPagination(p=>({...p,pageIndex:0}));}}>Urutkan kualitas</Button><Button size="sm" variant={topOnly?'default':'outline'} aria-pressed={topOnly} onClick={()=>{setTopOnly(value=>!value);setSorting([{id:'quality',desc:true}]);setPagination(p=>({...p,pageIndex:0}));}}>{topOnly?'Tampilkan semua':'Kandidat Top 10'}</Button></div></div>}
  <div className="table-toolbar"><div className="search-box"><Search size={17}/><Input aria-label="Cari nama atau grup" placeholder="Cari nama atau grup, misalnya BPA…" value={query} onChange={e=>{setQuery(e.target.value);setPagination(p=>({...p,pageIndex:0}));}}/></div><Select value={status} onValueChange={v=>{setStatus(v);setPagination(p=>({...p,pageIndex:0}));}}><SelectTrigger aria-label="Filter hasil" className="filter-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Semua hasil</SelectItem><SelectItem value="duplicates">Jawaban identik</SelectItem><SelectItem value="signals">Ada pola bahasa</SelectItem><SelectItem value="short">Teks singkat</SelectItem>{hasQuality&&<SelectItem value="reviewed">Penilaian dikonfirmasi</SelectItem>}</SelectContent></Select></div>
  <Table className={`results-table ${hasQuality?'with-quality':''}`}><TableHeader>{table.getHeaderGroups().map(h=><TableRow key={h.id}>{h.headers.map(col=><TableHead key={col.id}>{col.column.getCanSort()?<button onClick={col.column.getToggleSortingHandler()} className="sort-button">{flexRender(col.column.columnDef.header,col.getContext())}<ArrowUpDown size={13}/></button>:flexRender(col.column.columnDef.header,col.getContext())}</TableHead>)}</TableRow>)}</TableHeader><TableBody>{table.getRowModel().rows.map(row=><TableRow key={row.id}>{row.getVisibleCells().map(c=><TableCell key={c.id}>{flexRender(c.column.columnDef.cell,c.getContext())}</TableCell>)}</TableRow>)}{!filtered.length&&<TableRow><TableCell colSpan={columns.length} className="no-match">Tidak ada respons yang cocok. Coba ubah pencarian atau filter.</TableCell></TableRow>}</TableBody></Table>
  <div className="pagination"><span>{filtered.length?pagination.pageIndex*pagination.pageSize+1:0}–{Math.min((pagination.pageIndex+1)*pagination.pageSize,filtered.length)} dari {filtered.length.toLocaleString('id')} respons</span><div><Button variant="outline" size="icon" aria-label="Halaman sebelumnya" disabled={!table.getCanPreviousPage()} onClick={()=>table.previousPage()}><ChevronLeft size={17}/></Button><Button variant="outline" size="icon" aria-label="Halaman berikutnya" disabled={!table.getCanNextPage()} onClick={()=>table.nextPage()}><ChevronRight size={17}/></Button></div></div>
  <p className="table-note"><Info size={16}/>Jumlah identik menghitung pasangan kolom jawaban yang sama persis, termasuk peserta tersebut, pada seluruh file sebelum filter. Duplikasi tidak membuktikan penggunaan AI.</p>
  <Sheet open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><SheetContent className="participant-sheet"><SheetHeader><SheetTitle ref={participantTitleRef} tabIndex={-1}>{selected?.name}</SheetTitle><SheetDescription>{selected?.group} · Detail respons</SheetDescription></SheetHeader>{selected&&<div className="sheet-body" ref={participantBodyRef}><div className="authorship-note"><ShieldCheck size={18}/><p><strong>Status AI: tidak dapat ditentukan.</strong><br/>Temuan berikut adalah bahan peninjauan.</p></div><DuplicateMatches key={selected.id} rows={rows} selected={selected} onSelect={id=>{setSelected(id);requestAnimationFrame(()=>{participantBodyRef.current?.scrollTo({top:0});participantTitleRef.current?.focus({preventScroll:true});});}}/><Findings result={selected.analysis} compact/>{selected.quality&&<QualityReviewCard quality={selected.quality} onChange={quality=>{onReview(selected.id,quality);setPagination(p=>({...p,pageIndex:0}));}}/>}<section className="original-response"><h3>Jawaban 1</h3><p>{selected.response1||'Tidak ada jawaban.'}</p>{selected.response2&&<><h3>Jawaban 2</h3><p>{selected.response2}</p></>}</section></div>}</SheetContent></Sheet>
 </section>
}

export default function Home() {
 const [pdfBusy,setPdfBusy]=useState(false);
 const [batchRunId,setBatchRunId]=useState(0);const [qualityPrompt,setQualityPrompt]=useState('');const [quality,setQuality]=useState<QualityAssessment|null>(null);
 const [certificateOpened,setCertificateOpened]=useState(false);
 const [tab,setTab]=useState('text');const [text,setText]=useState('');const [result,setResult]=useState<TextAnalysis|null>(null);const [method,setMethod]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const [fileName,setFileName]=useState('');const [imported,setImported]=useState<Imported|null>(null);const [mapping,setMapping]=useState<Mapping>({name:'',group:'',response1:'',response2:'',duration:''});const [rows,setRows]=useState<Reviewed[]>([]);const [drag,setDrag]=useState(false);const fileRef=useRef<HTMLInputElement>(null);
 async function inspectText(){if(!text.trim()||busy)return;setBusy(true);setError('');await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));setResult(analyzeText(text));setQuality(assessQuality(text,qualityPrompt));setBusy(false);}
 async function exportTextPDF(){
  if(!result||pdfBusy)return;
  const snapshot={text,result,quality,date:new Date()};setPdfBusy(true);setError('');
  try {const {buildTextReport,loadReportFont,reportFilename}=await import('@/lib/pdf-report');const fontBase64=await loadReportFont();buildTextReport(snapshot.text,snapshot.result,{date:snapshot.date,fontBase64,quality:snapshot.quality}).save(reportFilename('teks',snapshot.date));}
  catch {setError('PDF belum dapat dibuat. Periksa koneksi untuk memuat pembuat laporan, lalu coba lagi.');}
  finally {setPdfBusy(false);}
 }
 async function upload(file?:File){if(!file||busy)return;setBusy(true);setError('');try{const d=await readFile(file);setImported(d);setMapping(autoMapping(d.headers));setFileName(file.name);setRows([]);}catch(e){setError(e instanceof Error?e.message:'File tidak dapat dibaca. Coba simpan ulang sebagai XLSX atau CSV.');}finally{setBusy(false);if(fileRef.current)fileRef.current.value='';}}
 async function inspectFile(){if(!imported)return;setBusy(true);setError('');await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));try{setRows(analyzeBatch(toParticipants(imported,mapping),qualityPrompt));setBatchRunId(value=>value+1);}catch(e){setError(e instanceof Error?e.message:'Pemeriksaan gagal. Periksa pemetaan kolom.');}finally{setBusy(false);}}
 function mapSelect(key:keyof Mapping,label:string,required=false){return <div className="mapping-field"><label id={`label-${key}`}>{label}{required&&<span> *</span>}</label><Select value={mapping[key]||'none'} onValueChange={value=>{setMapping(m=>({...m,[key]:value==='none'?'':value}));setRows([]);}}><SelectTrigger aria-labelledby={`label-${key}`}><SelectValue placeholder="Pilih kolom"/></SelectTrigger><SelectContent><SelectItem value="none">{required?'Pilih kolom':'Tidak digunakan'}</SelectItem>{imported?.headers.map((h,i)=><SelectItem key={i} value={String(i)}>{h} ({i+1})</SelectItem>)}</SelectContent></Select></div>;}
 return <div className="app-shell">
  <header className="topbar"><Link className="brand" href="/" aria-label="Telaah, halaman utama"><span className="brand-mark"><ScanText size={24} strokeWidth={1.8}/></span>telaah<span className="brand-period">.</span></Link><div className="topbar-right"><span className="workspace-label">Ruang pemeriksaan</span><button className="method-link" onClick={()=>setMethod(true)}><Info size={16}/>Cara kerja</button></div></header>
  <main className="workspace">
   <div className="page-heading"><div><div className="eyebrow heading-eyebrow"><span/>{tab==='certificate'?'SERTIFIKAT & APRESIASI':'ANALISIS TEKS & RESPONS'}</div><h1>{tab==='certificate'?'Buat sertifikat Anda':'Pemeriksa indikasi AI'}</h1><p>{tab==='certificate'?'Sesuaikan desain, logo, dan isi untuk setiap penerima.':'Kenali pola bahasa. Periksa duplikasi. Tinjau kualitas jawaban.'}</p></div><div className="local-badge"><LockKeyhole size={17}/><div><strong>Diproses di perangkat Anda</strong><span>Isi teks tidak dikirim ke layanan AI</span></div></div></div>
   {tab!=='certificate'&&<QualitySetup value={qualityPrompt} onChange={setQualityPrompt} disabled={busy}/>}
   <Tabs value={tab} onValueChange={v=>{setTab(v);setError('');if(v==='certificate')setCertificateOpened(true);}} className="workspace-tabs"><div className="tabs-row"><TabsList className="mode-tabs"><TabsTrigger value="text"><FileText size={17}/>Teks tunggal</TabsTrigger><TabsTrigger value="batch"><FileSpreadsheet size={17}/>File peserta</TabsTrigger><TabsTrigger value="certificate"><Award size={17}/>Sertifikat</TabsTrigger></TabsList><span className="method-version">{tab==='certificate'?'Desain sendiri · Unduh PDF':'Berbasis aturan, bukan model prediksi'}</span></div>
    <TabsContent value="text"><div className="analysis-grid"><section className="editor-card"><div className="card-header"><div><span className="step-label">01 / MASUKKAN TEKS</span><h2>Apa yang ingin Anda periksa?</h2></div><FileText size={23} className="muted"/></div><label htmlFor="analysis-text" className="sr-only">Teks yang akan diperiksa</label><Textarea id="analysis-text" className="text-editor" placeholder="Tempel jawaban, refleksi, atau tulisan di sini…" value={text} disabled={busy} maxLength={50000} onChange={e=>{setText(e.target.value);setResult(null);}} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();inspectText();}}}/><div className="editor-meta"><span>{countWords(text).toLocaleString('id')} kata <span className="meta-separator">/</span> {text.length.toLocaleString('id')} karakter</span>{text?<button disabled={busy} onClick={()=>{setText('');setResult(null);}}><X size={14}/>Bersihkan</button>:<button disabled={busy} onClick={()=>{setText(EXAMPLE);setResult(null);}}>Coba teks contoh<ArrowRight size={14}/></button>}</div><div className="editor-action"><p>Disarankan minimal 80 kata.<br/><span>Maksimal 50.000 karakter.</span></p><Button className="analyze-button" disabled={!text.trim()||busy} onClick={inspectText}>{busy?<LoaderCircle size={17} className="spin"/>:<ScanText size={18}/>}Periksa teks<ArrowRight size={17}/></Button></div><div className="editor-footnote"><LockKeyhole size={14}/>Teks hanya tersimpan selama halaman ini terbuka.</div></section>
    <section className="results-card" aria-live="polite"><div className="result-card-header"><span className="step-label">02 / TINJAU HASIL</span><div className="export-actions"><span className="subtle-pill">Bukan vonis AI</span>{result&&<Button variant="outline" size="sm" onClick={exportTextPDF} disabled={pdfBusy} aria-busy={pdfBusy}>{pdfBusy?<LoaderCircle size={15} className="spin"/>:<FileText size={15}/>}<span>{pdfBusy?'Membuat PDF…':'Unduh PDF'}</span></Button>}</div></div>{result?<><Findings result={result}/>{quality?<QualityReviewCard quality={quality} onChange={setQuality}/>:<p className="quality-empty">Untuk analisis kualitas, isi pertanyaan atau tujuan tugas di bagian atas lalu periksa teks kembali.</p>}</>:<div className="empty-result"><div className="scan-icon"><ScanText size={39} strokeWidth={1.3}/></div><h2>Setiap indikasi perlu konteks.</h2><p>Hasil pemeriksaan dan potongan teks yang mendasarinya akan muncul di sini.</p><div className="empty-checklist"><span><Braces size={17}/>Pola dan format bahasa</span><span><Fingerprint size={17}/>Frasa yang perlu ditinjau</span><span><ShieldCheck size={17}/>Penjelasan tanpa persentase AI</span></div></div>}</section></div></TabsContent>
    <TabsContent value="batch"><section className="upload-card"><div className="card-header"><div><span className="step-label">01 / IMPOR RESPONS</span><h2>Periksa satu file, banyak peserta.</h2></div><Button variant="outline" onClick={template}><ArrowDownToLine size={16}/>Template CSV</Button></div><input ref={fileRef} type="file" accept=".xlsx,.csv" className="sr-only" aria-label="Pilih file Excel atau CSV" onChange={e=>upload(e.target.files?.[0])}/>{!imported?<div className={`dropzone ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);upload(e.dataTransfer.files[0]);}}><div className="upload-icon">{busy?<LoaderCircle className="spin" size={29}/>:<UploadCloud size={29}/>}</div><h3>Tarik file Excel atau CSV ke sini</h3><p>Format ekspor Moodle didukung. Maksimal 10 MB dan 10.000 respons.</p><Button onClick={()=>fileRef.current?.click()} disabled={busy}>{busy?'Membaca file…':'Pilih file'}<ArrowRight size={16}/></Button><small>Lembar pertama dibaca. File diproses di perangkat Anda.</small></div>:<><div className="file-summary"><div className="file-summary-icon"><FileSpreadsheet size={25}/></div><div><strong>{fileName}</strong><p>{imported.rows.length.toLocaleString('id')} baris data · Lembar: {imported.sheet}</p></div><Button variant="ghost" onClick={()=>{setImported(null);setRows([]);setFileName('');setError('');}} disabled={busy}><X size={17}/>Ganti file</Button></div><div className="mapping-title"><h3>Sesuaikan kolom</h3><p>Periksa pilihan otomatis. Pada ekspor Moodle, nama peserta biasanya ada di <b>Last name</b> dan grup di <b>First name</b>.</p></div><div className="mapping-grid">{mapSelect('name','Nama peserta')}{mapSelect('group','Grup / bagian')}{mapSelect('response1','Jawaban 1',true)}{mapSelect('response2','Jawaban 2')}{mapSelect('duration','Durasi')}</div><div className="mapping-action"><p>Duplikasi dibandingkan pada seluruh file.<br/>Durasi tidak digunakan sebagai indikator AI.</p><Button className="analyze-button" disabled={busy||!mapping.response1} onClick={inspectFile}>{busy?<LoaderCircle className="spin" size={17}/>:<ScanText size={18}/>}Periksa {imported.rows.length.toLocaleString('id')} respons<ArrowRight size={17}/></Button></div></>}</section>{rows.length>0&&<ResultsTable key={`${fileName}-${JSON.stringify(mapping)}-${batchRunId}`} rows={rows} sourceName={fileName} onReview={(id,quality)=>setRows(current=>current.map(row=>row.id===id?{...row,quality}:row))}/>}</TabsContent>
    <TabsContent value="certificate" forceMount hidden={tab!=='certificate'}>{certificateOpened&&<CertificateStudio rows={rows} datasetKey={`${fileName}-${JSON.stringify(mapping)}-${batchRunId}`}/>}</TabsContent>
   </Tabs>
   {error&&<div className="error-message" role="alert"><Info size={18}/><p>{error}</p></div>}
   {tab!=='certificate'&&<aside className="understanding-note"><div className="note-icon"><ShieldCheck size={24}/></div><div><h3>Indikasi bukan bukti kepengarangan.</h3><p>Manusia bisa menulis sangat rapi. AI bisa menulis santai. Gunakan hasil untuk membuka percakapan, bukan menetapkan hukuman atau nilai peserta.</p></div><button onClick={()=>setMethod(true)}>Pahami batasannya<ArrowRight size={16}/></button></aside>}
   <footer className="page-footer"><span>telaah. <span>·</span> Pemeriksaan yang bisa dijelaskan</span><span>Rubrik kualitas terpisah dari indikasi AI</span></footer>
  </main>
  <Dialog open={method} onOpenChange={setMethod}><DialogContent className="method-dialog"><DialogHeader><DialogTitle>Cara kerja Telaah</DialogTitle><DialogDescription>Pahami apa yang diperiksa dan apa yang tidak dapat disimpulkan.</DialogDescription></DialogHeader><div className="method-content"><section><span>01</span><div><h3>Pola bahasa dengan aturan terbuka</h3><p>Penyebutan identitas asisten AI, sisa label percakapan, placeholder, dan pengantar jawaban ditandai secara literal. Empat baris berformat poin pada teks minimal 80 kata, atau empat penghubung formal pada teks minimal 100 kata, juga ditampilkan.</p><p>Ambang tersebut adalah aturan praktis, bukan hasil kalibrasi pada data manusia dan AI. Tidak ada sensitivitas, akurasi, atau persentase AI yang diklaim.</p></div></section><section><span>02</span><div><h3>Kecocokan teks dalam satu file</h3><p>Jawaban 1 dan 2 dibandingkan sebagai pasangan. Kecocokan persis tidak mengubah huruf atau spasi. Tampilan detail juga menghitung kecocokan setelah Unicode, huruf kecil, dan spasi diseragamkan. Jika hanya satu kolom dipilih, teks itu yang dibandingkan. Teks kosong tidak dianggap duplikat.</p><p>Ini bukan pencarian plagiarisme di internet atau pendeteksi parafrasa. Kecocokan tidak menentukan penulis asli atau sumber AI.</p></div></section><section><span>03</span><div><h3>Peninjauan manusia tetap diperlukan</h3><p>Rubrik kualitas aktif bila acuan tugas diisi. Relevansi, kedalaman refleksi, contoh konkret, dan rencana tindakan masing-masing berbobot 25 poin. Skor awal memakai kecocokan kata dan aturan bahasa; belum memahami makna. Buka detail untuk memeriksa bukti, mengoreksi tingkat 0–4, dan mengonfirmasi penilaian. Peringkat dalam filter aktif menggunakan skor rubrik saat ini, termasuk koreksi reviewer. Nilai seri berbagi peringkat. Dua jawaban digabung sebagai satu refleksi; ini bukan pemeriksaan kebenaran fakta atau nilai final. Durasi, panjang teks, nada kritis, duplikasi, dan indikasi AI tidak memberi penalti otomatis.</p></div></section><section><span>04</span><div><h3>Data tetap di perangkat</h3><p>Analisis berjalan di browser. Isi teks dan file tidak dikirim ke layanan AI atau disimpan oleh aplikasi. Memuat ulang halaman menghapus hasil. Unduhan CSV dan PDF dibuat di perangkat Anda serta berisi data yang diperiksa; simpan dan bagikan sesuai kebutuhan Anda.</p></div></section><div className="method-disclosure"><Info size={18}/><p>{MODEL_NOTE} {QUALITY_NOTE}</p></div></div></DialogContent></Dialog>
 </div>;
}
