"use client";

import { useEffect, useId, useMemo, useRef, useState } from "react";
import { Archive, Award, BadgeCheck, ChevronLeft, ChevronRight, Download, FileUp, ImagePlus, LoaderCircle, Mail, QrCode, RotateCcw, Save, ShieldCheck, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { CERTIFICATE_FIELDS, CERTIFICATE_LIMIT, CERTIFICATE_TEMPLATES, decodeCertificateImage, defaultCertificateDesign, loadCertificateImage, manualCertificateRecipients, parseCertificateDesign, validateCertificateBatch, type CertificateDesign, type CertificateRecipient } from "@/lib/certificate";
import { loadReportFont } from "@/lib/pdf-font";
import { qualityScore, rankQuality } from "@/lib/quality";
import { exportIssuerBackup, issueCertificates, loadIssuances, setIssuanceStatus, type IssuanceRecord } from "@/lib/certificate-identity";
import type { Reviewed } from "@/lib/analysis";
import type { CertificateScene } from "@/lib/certificate-render";

type AssetKey = "logo1" | "logo2" | "signature1" | "signature2" | "background";
const ASSETS = [
  { key: "logo1", label: "Logo utama" }, { key: "logo2", label: "Logo kedua (opsional)" },
  { key: "signature1", label: "Tanda tangan 1 (opsional)" }, { key: "signature2", label: "Tanda tangan 2 (opsional)" },
] as const;
const PROJECTS_KEY = "telaah-certificate-projects-v1";
type SavedProject = { id: string; name: string; updatedAt: string; design: CertificateDesign; names: string; mode: "manual" | "file"; ids: number[] };

function saveBlob(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function saveFile(content: string, filename: string, type: string) { saveBlob(new Blob([content], { type }), filename); }
function safeName(value: string) { return value.replace(/[^\p{L}\p{N}-]+/gu, "-").replace(/^-|-$/g, "").slice(0, 60) || "penerima"; }
function asBase64(buffer: ArrayBuffer) { const bytes = new Uint8Array(buffer); let value = ""; for (let i = 0; i < bytes.length; i += 8192) value += String.fromCharCode(...bytes.subarray(i, i + 8192)); return btoa(value); }
function readProjects(): SavedProject[] { try { const value = JSON.parse(localStorage.getItem(PROJECTS_KEY) ?? "[]"); return Array.isArray(value) ? value : []; } catch { return []; } }

function CertificatePreview({ scene, name, editable, design, onOffset }: { scene: CertificateScene; name: string; editable: boolean; design: CertificateDesign; onOffset: (key: "nameOffsetY" | "bodyOffsetY" | "signatureOffsetY", value: number) => void }) {
  const drag = (key: "nameOffsetY" | "bodyOffsetY" | "signatureOffsetY", base: number) => (event: React.PointerEvent<SVGGElement>) => {
    const svg = event.currentTarget.ownerSVGElement!; const rect = svg.getBoundingClientRect();
    const move = (pointer: PointerEvent) => onOffset(key, Math.max(-12, Math.min(12, Math.round(((pointer.clientY - rect.top) / rect.height) * 210 - base))));
    const end = () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", end); };
    window.addEventListener("pointermove", move); window.addEventListener("pointerup", end, { once: true });
  };
  const handles = [["nameOffsetY", 106, design.nameOffsetY, "nama"], ["bodyOffsetY", 143, design.bodyOffsetY, "isi"], ["signatureOffsetY", 179, design.signatureOffsetY, "tanda tangan"]] as const;
  return <svg viewBox="0 0 297 210" className="certificate-preview" role="img" aria-label={`Pratinjau sertifikat untuk ${name}`}>
    {scene.nodes.map((node, index) => {
      if (node.kind === "text") { const family = node.family === "times" ? "Georgia, serif" : node.family === "courier" ? "Courier New, monospace" : "TelaahCertificate, sans-serif"; return <text key={index} x={node.x} y={node.y} fill={node.color} fontFamily={family} fontSize={(node.size * 25.4) / 72} textAnchor={node.align === "center" ? "middle" : "start"} xmlSpace="preserve">{node.text}</text>; }
      if (node.kind === "image") return <image key={index} href={node.data} x={node.x} y={node.y} width={node.width} height={node.height} />;
      if (node.kind === "line") return <line key={index} x1={node.x} y1={node.y} x2={node.x2} y2={node.y2} stroke={node.stroke} strokeWidth={node.strokeWidth} />;
      const paint = { fill: node.fill ?? "none", stroke: node.stroke ?? "none", strokeWidth: node.strokeWidth };
      if (node.kind === "rect") return <rect key={index} x={node.x} y={node.y} width={node.width} height={node.height} {...paint} />;
      if (node.kind === "circle") return <circle key={index} cx={node.x} cy={node.y} r={node.radius} {...paint} />;
      return <polygon key={index} points={node.points.map((point) => point.join(",")).join(" ")} {...paint} />;
    })}
    {editable && handles.map(([key, base, offset, label]) => <g key={key} className="layout-handle" onPointerDown={drag(key, base)} role="button" tabIndex={0} aria-label={`Geser ${label}`}><line x1="280" x2="295" y1={base + offset} y2={base + offset} /><circle cx="287" cy={base + offset} r="3.3" /><title>Seret vertikal: {label}</title></g>)}
  </svg>;
}

export default function CertificateStudio({ rows, datasetKey }: { rows: Reviewed[]; datasetKey: string }) {
  const id = useId();
  const [design, setDesign] = useState<CertificateDesign>(() => defaultCertificateDesign());
  const [mode, setMode] = useState<"manual" | "file">("manual"); const [names, setNames] = useState("");
  const [selection, setSelection] = useState<{ datasetKey: string; ids: number[] }>({ datasetKey: "", ids: [] });
  const [query, setQuery] = useState(""); const [page, setPage] = useState(0); const [previewIndex, setPreviewIndex] = useState(0);
  const [working, setWorking] = useState<"pdf" | "zip" | "email" | "image" | "design" | null>(null); const [progress, setProgress] = useState(0);
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [includeQR, setIncludeQR] = useState(true); const [layoutEditing, setLayoutEditing] = useState(false); const [adminKey, setAdminKey] = useState("");
  const [issuances, setIssuances] = useState<IssuanceRecord[]>([]); const [projects, setProjects] = useState<SavedProject[]>([]);
  const designFile = useRef<HTMLInputElement>(null); const assetRefs = useRef<Partial<Record<AssetKey, HTMLInputElement | null>>>({});
  useEffect(() => { setIssuances(loadIssuances()); setProjects(readProjects()); }, []);

  const chosen = useMemo(() => new Set(selection.datasetKey === datasetKey ? selection.ids : []), [selection, datasetKey]);
  const matchingRows = useMemo(() => rows.filter((row) => `${row.name} ${row.group}`.toLocaleLowerCase("id").includes(query.trim().toLocaleLowerCase("id"))), [rows, query]);
  const currentPage = Math.min(page, Math.max(0, Math.ceil(matchingRows.length / 20) - 1));
  const recipientsState = useMemo(() => { try { const recipients: CertificateRecipient[] = mode === "manual" ? manualCertificateRecipients(names) : rows.filter((row) => chosen.has(row.id)).map((row) => ({ id: `file-${row.id}`, name: row.name, group: row.group, email: row.email })); return { recipients, error: "" }; } catch (cause) { return { recipients: [], error: cause instanceof Error ? cause.message : "Daftar penerima tidak valid." }; } }, [mode, names, rows, chosen]);
  const recipients = recipientsState.recipients; const currentIndex = Math.min(previewIndex, Math.max(0, recipients.length - 1));
  const recipient = useMemo(() => recipients[currentIndex] ?? { id: "example", name: "Nama Peserta", group: "Grup / bagian" }, [recipients, currentIndex]);
  const [retry, setRetry] = useState(0); const snapshot = useMemo(() => ({ design, recipient, index: currentIndex, retry }), [design, recipient, currentIndex, retry]);
  const [preview, setPreview] = useState<{ snapshot: typeof snapshot; scene?: CertificateScene; error?: string } | null>(null); const previewPending = preview?.snapshot !== snapshot; const previewError = preview?.snapshot === snapshot ? preview.error : "";
  useEffect(() => { let cancelled = false; const timer = setTimeout(async () => { try { const [{ previewCertificate }, font] = await Promise.all([import("@/lib/certificate-render"), loadReportFont()]); await document.fonts.load("16px TelaahCertificate"); const scene = previewCertificate(snapshot.design, snapshot.recipient, snapshot.index, font); if (!cancelled) setPreview({ snapshot, scene }); } catch (cause) { if (!cancelled) setPreview({ snapshot, error: cause instanceof Error ? cause.message : "Pratinjau belum dapat dibuat." }); } }, 220); return () => { cancelled = true; clearTimeout(timer); }; }, [snapshot]);

  function update<K extends keyof CertificateDesign>(key: K, value: CertificateDesign[K]) { setDesign((current) => ({ ...current, [key]: value })); setError(""); setNotice(""); }
  function field(key: keyof CertificateDesign, multiline = false) { const config = CERTIFICATE_FIELDS.find((item) => item.key === key)!; const props = { id: `${id}-${key}`, value: String(design[key]), maxLength: config.max, onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => update(key, event.target.value) }; return <label className="certificate-field" htmlFor={props.id}><span>{config.label}</span>{multiline ? <Textarea {...props} rows={4} /> : <Input {...props} />}</label>; }
  async function uploadImage(key: AssetKey, file?: File) { if (!file || working) return; setWorking("image"); setError(""); try { update(key, await loadCertificateImage(file)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Gambar tidak dapat dimuat."); } finally { setWorking(null); if (assetRefs.current[key]) assetRefs.current[key]!.value = ""; } }
  async function importDesign(file?: File) { if (!file || working) return; setWorking("design"); setError(""); try { if (file.size > 12 * 1024 * 1024) throw new Error("File desain maksimal 12 MB."); const next = parseCertificateDesign(JSON.parse(await file.text())); await Promise.all(([...ASSETS, { key: "background" as const, label: "Latar" }]).map((asset) => next[asset.key] ? decodeCertificateImage(next[asset.key]!.data) : Promise.resolve())); setDesign(next); setNotice("Desain dimuat. Periksa penerima dan nomor awal."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Desain tidak dapat dimuat."); } finally { setWorking(null); if (designFile.current) designFile.current.value = ""; } }
  function exportDesign() { try { const valid = parseCertificateDesign(design); saveFile(JSON.stringify(valid, null, 2), `desain-sertifikat-${valid.template}.json`, "application/json"); setNotice("Desain berhasil diekspor."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Desain tidak dapat disimpan."); } }
  function saveProject() { const name = window.prompt("Nama proyek sertifikat", `${design.event || "Sertifikat"} · ${new Date().toLocaleDateString("id-ID")}`)?.trim(); if (!name) return; const project: SavedProject = { id: crypto.randomUUID(), name: name.slice(0, 80), updatedAt: new Date().toISOString(), design, names, mode, ids: [...chosen] }; const next = [project, ...projects].slice(0, 20); localStorage.setItem(PROJECTS_KEY, JSON.stringify(next)); setProjects(next); setNotice(`Proyek “${project.name}” disimpan di perangkat ini.`); }
  function openProject(project: SavedProject) { setDesign(parseCertificateDesign(project.design)); setNames(project.names); setMode(project.mode); setSelection({ datasetKey, ids: project.ids }); setPreviewIndex(0); setNotice(`Proyek “${project.name}” dimuat.`); }
  function removeProject(projectId: string) { const next = projects.filter((project) => project.id !== projectId); localStorage.setItem(PROJECTS_KEY, JSON.stringify(next)); setProjects(next); }
  function selectIds(ids: number[]) { const unique = [...new Set(ids)]; if (unique.length > CERTIFICATE_LIMIT) { setError(`Maksimal ${CERTIFICATE_LIMIT} penerima per penerbitan.`); return; } setSelection({ datasetKey, ids: unique }); setError(""); }
  function selectQuality(kind: "top" | "confirmed") { const candidates = rankQuality(rows).filter((row) => kind === "top" ? row.qualityRank !== undefined && row.qualityRank <= 10 : row.quality?.confirmed).map((row) => row.id).slice(0, CERTIFICATE_LIMIT); selectIds(candidates); setMode("file"); setPreviewIndex(0); setNotice(kind === "top" ? `${candidates.length} kandidat Top 10 dipilih. Periksa kembali sebelum menerbitkan.` : `${candidates.length} peserta dengan nilai reviewer terkonfirmasi dipilih.`); }
  async function prepare(single: boolean) { if (recipientsState.error) throw new Error(recipientsState.error); const target = single ? recipients.slice(currentIndex, currentIndex + 1) : recipients; const config = single ? { ...design, startNumber: design.startNumber + currentIndex } : design; validateCertificateBatch(config, target); if (!includeQR) return { config, target }; const issued = await issueCertificates(config, target, window.location.origin); setIssuances(loadIssuances()); return { config, target: issued.recipients }; }
  async function downloadPDF(single: boolean) { if (working) return; setError(""); setNotice(""); try { setWorking("pdf"); setProgress(0); const [{ config, target }, { buildCertificates }, font] = await Promise.all([prepare(single), import("@/lib/certificate-render"), loadReportFont()]); const pdf = await buildCertificates(config, target, font, setProgress); pdf.save(`sertifikat-${single ? safeName(target[0].name) : `${target.length}-penerima`}-${config.date}.pdf`); setNotice(`${target.length} sertifikat berhasil dibuat${includeQR ? " dan dicatat dalam registri" : ""}.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "PDF belum dapat dibuat."); } finally { setWorking(null); } }
  async function downloadZIP() { if (working) return; setError(""); setNotice(""); setWorking("zip"); setProgress(0); try { const [{ config, target }, { buildCertificates }, { default: JSZip }, font] = await Promise.all([prepare(false), import("@/lib/certificate-render"), import("jszip"), loadReportFont()]); const zip = new JSZip(); for (let index = 0; index < target.length; index++) { const pdf = await buildCertificates({ ...config, startNumber: config.startNumber + index }, [target[index]], font); zip.file(`${String(index + 1).padStart(3, "0")}-${safeName(target[index].name)}.pdf`, pdf.output("arraybuffer")); setProgress(index + 1); } saveBlob(await zip.generateAsync({ type: "blob", compression: "DEFLATE" }), `sertifikat-${target.length}-penerima.zip`); setNotice(`${target.length} PDF individual berhasil dikemas dalam ZIP.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "ZIP belum dapat dibuat."); } finally { setWorking(null); } }
  async function sendEmails() { if (working) return; const targets = recipients.filter((item) => item.email); if (!adminKey.trim()) { setError("Masukkan kunci admin email terlebih dahulu."); return; } if (!targets.length) { setError("Belum ada penerima dengan email."); return; } if (targets.length > 20) { setError("Pengiriman sekaligus dibatasi 20 email."); return; } if (!window.confirm(`Kirim sertifikat ke ${targets.length} alamat email?`)) return; setWorking("email"); setError(""); setProgress(0); try { const issued = await issueCertificates(design, targets, window.location.origin); const [{ buildCertificates }, font] = await Promise.all([import("@/lib/certificate-render"), loadReportFont()]); for (let index = 0; index < issued.recipients.length; index++) { const target = issued.recipients[index]; const originalIndex = Math.max(0, recipients.findIndex((item) => item.id === target.id)); const pdf = await buildCertificates({ ...design, startNumber: design.startNumber + originalIndex }, [target], font); const response = await fetch("/api/certificates/email", { method: "POST", headers: { "content-type": "application/json", "x-admin-key": adminKey }, body: JSON.stringify({ to: target.email, name: target.name, subject: design.title, filename: `sertifikat-${safeName(target.name)}.pdf`, pdfBase64: asBase64(pdf.output("arraybuffer")) }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || `Pengiriman untuk ${target.name} gagal.`); setProgress(index + 1); } setIssuances(loadIssuances()); setNotice(`${targets.length} sertifikat berhasil dikirim melalui email.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Email belum dapat dikirim."); } finally { setWorking(null); } }

  const busy = !!working;
  return <section className="certificate-studio">
    <header className="certificate-studio-heading"><div><span className="eyebrow">STUDIO SERTIFIKAT</span><h2>Desain, terbitkan, dan verifikasi.</h2><p>Buat PDF individual, ZIP massal, QR verifikasi, dan registri penerbitan.</p></div><div className="export-actions"><Button variant="outline" disabled={busy} onClick={() => designFile.current?.click()}><FileUp size={16} />Muat desain</Button><Button variant="outline" disabled={busy} onClick={exportDesign}><Save size={16} />Ekspor desain</Button><Button variant="outline" disabled={busy} onClick={saveProject}><Archive size={16} />Simpan proyek</Button><input ref={designFile} type="file" accept=".json,application/json" className="sr-only" aria-label="Muat desain sertifikat" onChange={(event) => importDesign(event.target.files?.[0])} /></div></header>
    {projects.length > 0 && <details className="certificate-projects"><summary>Proyek tersimpan di perangkat <span>{projects.length}</span></summary><div>{projects.map((project) => <article key={project.id}><button type="button" onClick={() => openProject(project)}><strong>{project.name}</strong><small>{new Date(project.updatedAt).toLocaleString("id-ID")}</small></button><Button variant="ghost" size="icon" aria-label={`Hapus ${project.name}`} onClick={() => removeProject(project.id)}><Trash2 size={15} /></Button></article>)}</div></details>}
    <div className="certificate-template-heading"><strong>{CERTIFICATE_TEMPLATES.length} pilihan desain</strong><span>Atau unggah latar A4 mendatar milik Anda</span></div>
    <div className="certificate-templates" role="group" aria-label="Pilih template sertifikat">{CERTIFICATE_TEMPLATES.map((template) => <button type="button" key={template.id} className={`certificate-template ${design.template === template.id ? "selected" : ""}`} aria-pressed={design.template === template.id} disabled={busy} onClick={() => setDesign((current) => ({ ...current, template: template.id, ink: template.ink, accent: template.accent }))}><span className={`template-swatch swatch-${template.id}`} style={{ "--template-ink": template.ink, "--template-accent": template.accent } as React.CSSProperties}><Award size={23} /><i /><i /></span><strong>{template.name}</strong><small>{template.description}</small></button>)}</div>
    <div className="certificate-layout"><fieldset className="certificate-controls" disabled={busy}>
      <details open className="certificate-panel"><summary>Penerima sertifikat <span>{recipients.length} dipilih</span></summary><div className="certificate-panel-body"><div className="certificate-mode" role="group" aria-label="Sumber penerima"><button type="button" aria-pressed={mode === "manual"} onClick={() => { setMode("manual"); setPreviewIndex(0); }}>Isi manual</button><button type="button" aria-pressed={mode === "file"} onClick={() => { setMode("file"); setPreviewIndex(0); }}>Dari file peserta</button></div>
        {mode === "manual" ? <label className="certificate-field"><span>Nama penerima</span><Textarea rows={5} maxLength={50000} value={names} onChange={(event) => { setNames(event.target.value); setPreviewIndex(0); }} placeholder={"Nama Peserta | BPA | email@contoh.com\nNama Lain | BTI"} /><small>Satu penerima per baris: Nama | Grup | Email. Grup dan email opsional.</small></label> : !rows.length ? <p className="certificate-help">Unggah dan periksa file pada tab <strong>File peserta</strong>, lalu kembali ke sini.</p> : <div className="certificate-recipient-picker"><Input aria-label="Cari penerima" placeholder="Cari nama atau grup…" value={query} onChange={(event) => { setQuery(event.target.value); setPage(0); }} /><div className="certificate-selection-actions"><button type="button" onClick={() => selectIds([...chosen, ...matchingRows.map((row) => row.id)])}>Pilih hasil ({matchingRows.length})</button><button type="button" onClick={() => selectQuality("top")}>Kandidat Top 10</button><button type="button" onClick={() => selectQuality("confirmed")}>Nilai terkonfirmasi</button><button type="button" onClick={() => selectIds([])}>Kosongkan</button></div><div className="certificate-recipient-list">{matchingRows.slice(currentPage * 20, (currentPage + 1) * 20).map((row) => <label key={row.id}><input type="checkbox" checked={chosen.has(row.id)} onChange={(event) => selectIds(event.target.checked ? [...chosen, row.id] : [...chosen].filter((item) => item !== row.id))} /><span>{row.name}<small>{row.group} · {row.quality ? `Kualitas ${qualityScore(row.quality)}/100` : "Belum dinilai"}{row.email ? ` · ${row.email}` : ""}</small></span></label>)}{!matchingRows.length && <p>Tidak ada peserta yang cocok.</p>}</div>{matchingRows.length > 20 && <div className="certificate-picker-pages"><button type="button" disabled={currentPage === 0} onClick={() => setPage(currentPage - 1)}>Sebelumnya</button><span>{currentPage + 1} / {Math.ceil(matchingRows.length / 20)}</span><button type="button" disabled={(currentPage + 1) * 20 >= matchingRows.length} onClick={() => setPage(currentPage + 1)}>Berikutnya</button></div>}<p className="certificate-help">Kandidat kualitas tidak diterbitkan otomatis. Anda tetap dapat meninjau dan mengubah pilihan.</p></div>}
        <label className="certificate-check"><input type="checkbox" checked={design.showGroup} onChange={(event) => update("showGroup", event.target.checked)} />Tampilkan grup di bawah nama</label></div></details>
      <details open className="certificate-panel"><summary>Isi sertifikat</summary><div className="certificate-panel-body">{field("organizer")}{field("title")}{field("subtitle")}{field("introduction")}{field("event")}{field("body", true)}<p className="certificate-help">Variabel: {"{nama}"}, {"{grup}"}, {"{acara}"}, {"{penyelenggara}"}, {"{tanggal}"}, {"{tempat}"}, {"{nomor}"}.</p></div></details>
      <details className="certificate-panel"><summary>Tampilan &amp; tata letak</summary><div className="certificate-panel-body"><div className="certificate-colors"><label>Warna teks<input type="color" value={design.ink} onChange={(event) => update("ink", event.target.value)} /></label><label>Warna aksen<input type="color" value={design.accent} onChange={(event) => update("accent", event.target.value)} /></label></div><label className="certificate-field"><span>Jenis huruf</span><select value={design.fontFamily} onChange={(event) => update("fontFamily", event.target.value as CertificateDesign["fontFamily"])}><option value="sans">Sans modern</option><option value="serif">Serif formal</option><option value="mono">Mono teknis</option></select></label><label className="certificate-range"><span>Skala huruf <b>{Math.round(design.fontScale * 100)}%</b></span><input type="range" min="0.8" max="1.2" step="0.05" value={design.fontScale} onChange={(event) => update("fontScale", Number(event.target.value))} /></label>{(["nameOffsetY", "bodyOffsetY", "signatureOffsetY"] as const).map((key, index) => <label className="certificate-range" key={key}><span>Posisi {index === 0 ? "nama" : index === 1 ? "isi" : "tanda tangan"} <b>{design[key] > 0 ? "+" : ""}{design[key]}</b></span><input type="range" min="-12" max="12" value={design[key]} onChange={(event) => update(key, Number(event.target.value))} /></label>)}<div className="certificate-layout-actions"><Button type="button" size="sm" variant={layoutEditing ? "default" : "outline"} onClick={() => setLayoutEditing((value) => !value)}>{layoutEditing ? "Selesai menggeser" : "Geser di pratinjau"}</Button><Button type="button" size="sm" variant="ghost" onClick={() => setDesign((current) => ({ ...current, fontScale: 1, nameOffsetY: 0, bodyOffsetY: 0, signatureOffsetY: 0 }))}><RotateCcw size={14} />Reset</Button></div><div className="certificate-asset"><span>Latar kustom A4 mendatar</span><div><Button type="button" variant="outline" size="sm" onClick={() => assetRefs.current.background?.click()}><ImagePlus size={15} />{design.background ? "Ganti latar" : "Unggah latar"}</Button>{design.background && <Button type="button" variant="ghost" size="icon" aria-label="Hapus latar" onClick={() => update("background", null)}><Trash2 size={15} /></Button>}</div></div><label className="certificate-check"><input type="checkbox" checked={design.useTemplateFrame} onChange={(event) => update("useTemplateFrame", event.target.checked)} />Tampilkan bingkai template di atas latar</label></div></details>
      <details className="certificate-panel"><summary>Nomor, tanggal &amp; catatan</summary><div className="certificate-panel-body">{field("numberPattern")}<label className="certificate-field"><span>Nomor awal</span><Input type="number" min={1} max={999999} value={design.startNumber} onChange={(event) => update("startNumber", Number(event.target.value))} /></label><label className="certificate-field"><span>Tanggal kegiatan</span><Input type="date" value={design.date} onChange={(event) => update("date", event.target.value)} /></label>{field("place")}{field("dateLine")}{field("footer")}</div></details>
      <details className="certificate-panel"><summary>Logo &amp; penandatangan</summary><div className="certificate-panel-body">{ASSETS.slice(0, 2).map((asset) => <AssetControl key={asset.key} asset={asset} image={design[asset.key]} onUpload={() => assetRefs.current[asset.key]?.click()} onRemove={() => update(asset.key, null)} />)}{field("signer1")}{field("role1")}{field("signer2")}{field("role2")}{ASSETS.slice(2).map((asset) => <AssetControl key={asset.key} asset={asset} image={design[asset.key]} onUpload={() => assetRefs.current[asset.key]?.click()} onRemove={() => update(asset.key, null)} />)}</div></details>
      <details className="certificate-panel"><summary>Verifikasi &amp; email</summary><div className="certificate-panel-body"><label className="certificate-check"><input type="checkbox" checked={includeQR} onChange={(event) => setIncludeQR(event.target.checked)} /><QrCode size={16} />QR verifikasi bertanda tangan digital</label><label className="certificate-field"><span>Kunci admin email</span><Input type="password" autoComplete="off" value={adminKey} onChange={(event) => setAdminKey(event.target.value)} placeholder="Sesuai CERTIFICATE_ADMIN_KEY di Vercel" /></label><p className="certificate-help">Email aktif setelah tiga variabel Resend dipasang di Vercel. Kunci ini hanya disimpan selama halaman terbuka.</p><Button type="button" variant="outline" disabled={busy || !recipients.some((item) => item.email)} onClick={sendEmails}><Mail size={16} />{working === "email" ? `Mengirim ${progress}/${recipients.filter((item) => item.email).length}…` : `Kirim email (${recipients.filter((item) => item.email).length})`}</Button></div></details>
      {([...ASSETS, { key: "background" as const, label: "Latar kustom" }]).map((asset) => <input key={asset.key} ref={(element) => { assetRefs.current[asset.key] = element; }} type="file" accept="image/png,image/jpeg" className="sr-only" aria-label={`Pilih ${asset.label}`} onChange={(event) => uploadImage(asset.key, event.target.files?.[0])} />)}
    </fieldset>
    <div className="certificate-preview-column"><div className="certificate-preview-card"><div className="certificate-preview-heading"><strong>Pratinjau langsung</strong><span>A4 · Mendatar</span></div><div className={`certificate-paper ${layoutEditing ? "editing" : ""}`}>{preview?.scene && !previewError ? <CertificatePreview scene={preview.scene} name={recipient.name} editable={layoutEditing} design={design} onOffset={(key, value) => update(key, value)} /> : <div className="certificate-preview-empty"><Award size={40} /><p>{previewError || "Menyiapkan pratinjau sertifikat…"}</p>{previewError && <Button variant="outline" disabled={busy} onClick={() => setRetry((value) => value + 1)}>Coba lagi</Button>}</div>}{previewPending && <div className="certificate-refresh" role="status"><LoaderCircle className="spin" size={16} />Memperbarui…</div>}</div><div className="certificate-preview-pages"><span>{recipients.length ? `${currentIndex + 1} dari ${recipients.length}` : "Contoh tampilan"}</span><div><Button variant="outline" size="icon" disabled={currentIndex === 0 || busy} aria-label="Sebelumnya" onClick={() => setPreviewIndex(currentIndex - 1)}><ChevronLeft size={16} /></Button><Button variant="outline" size="icon" disabled={currentIndex + 1 >= recipients.length || busy} aria-label="Berikutnya" onClick={() => setPreviewIndex(currentIndex + 1)}><ChevronRight size={16} /></Button></div></div></div>
      {(error || recipientsState.error) && <p className="error-message" role="alert">{error || recipientsState.error}</p>}{notice && <p className="certificate-notice" role="status">{notice}</p>}
      <div className="certificate-downloads"><Button variant="outline" disabled={busy || !recipients.length || previewPending || !!previewError || !!recipientsState.error} onClick={() => downloadPDF(true)}><Download size={16} />PDF penerima ini</Button><Button variant="outline" disabled={busy || !recipients.length || previewPending || !!previewError || !!recipientsState.error} onClick={downloadZIP}>{working === "zip" ? <LoaderCircle size={16} className="spin" /> : <Archive size={16} />}{working === "zip" ? `ZIP ${progress}/${recipients.length}` : "ZIP individual"}</Button><Button disabled={busy || !recipients.length || previewPending || !!previewError || !!recipientsState.error} onClick={() => downloadPDF(false)}>{working === "pdf" ? <LoaderCircle size={17} className="spin" /> : <Download size={17} />}{working === "pdf" ? `Membuat ${progress}…` : `PDF gabungan (${recipients.length})`}</Button></div>
      <details className="issuance-dashboard"><summary><ShieldCheck size={17} />Registri penerbitan <span>{issuances.length}</span></summary><div className="issuance-actions"><Button size="sm" variant="outline" disabled={!issuances.length} onClick={() => saveFile(exportIssuerBackup(), "cadangan-registri-sertifikat.json", "application/json")}><Save size={14} />Cadangkan</Button></div><div className="issuance-list">{issuances.slice(0, 30).map((item) => <article key={item.id}><BadgeCheck size={17} /><div><strong>{item.name}</strong><small>{item.number || item.id.slice(0, 8)} · {new Date(item.issuedAt).toLocaleString("id-ID")}</small><small className={item.status}>{item.status === "active" ? "Aktif" : "Dicabut"} · {item.fingerprint}</small></div><Button size="sm" variant="ghost" onClick={() => setIssuances(setIssuanceStatus(item.id, item.status === "active" ? "revoked" : "active"))}>{item.status === "active" ? "Cabut" : "Aktifkan"}</Button></article>)}{!issuances.length && <p>Belum ada sertifikat ber-QR di perangkat ini.</p>}</div><p className="certificate-help">Tanda tangan QR dapat diverifikasi lintas perangkat. Status pencabutan masih lokal sampai database online dihubungkan.</p></details>
    </div></div>
  </section>;
}

function AssetControl({ asset, image, onUpload, onRemove }: { asset: { key: AssetKey; label: string }; image: unknown; onUpload: () => void; onRemove: () => void }) {
  return <div className="certificate-asset"><span>{asset.label}</span><div><Button type="button" variant="outline" size="sm" onClick={onUpload}><ImagePlus size={15} />{image ? "Ganti" : "Unggah"}</Button>{!!image && <Button type="button" variant="ghost" size="icon" aria-label={`Hapus ${asset.label}`} onClick={onRemove}><Trash2 size={15} /></Button>}</div></div>;
}
